### ISSUE TITLE
I need IDB please! (Preciso do IDB, obrigado!)

### ISSUE THREAD

**Issue by BohanRen** [keowu/mhyprot2#2]
Preciso do IDB, obrigado!
Meu e-mail é `renbohan233@gmail.com`

**Comment by keowu** [comment]
Hello BobH, 

Firstly thank you for your issue, I emailed you with a link to download IDB in your email informed, I hope that IDB can contribute to your learning!

For better work use the following version of IDA:
IDA 7.5 SP3 or superior

**Comment by jmpoep** [comment]
Preciso do IDB, obrigado!
Meu e-mail é `shenouyuan19820113@163.com`
Thank you！

**Comment by keowu** [comment]
Hello jmpoep,

Sorry for the delay, I sent you an email with the download link, I hope it will be useful for your studies.

For better work use the following version of IDA:
IDA 7.5 SP3 or superior

**Comment by keowu** [comment]
Hello phildev4,

I sent an email with the download link, hope it's helpful.

For better work use the following version of IDA:
IDA 7.5 SP3 or superior

**Comment by phildev4** [comment]
Thanks!

**Comment by Valdoivre** [comment]
May I also get it?

**Comment by Valdoivre** [comment]
May I also get it?
My mail is valdoivre@hotmail.com
Thank you!

**Comment by keowu** [comment]
Hello Valdoivre,

I sent the IDB in your E-mail, I hope it's useful for your learning.

For better work use the following version of IDA:
IDA 7.5 SP3 or superior

**Comment by Valdoivre** [comment]
Thank you！

**Comment by AdminXYZ666** [comment]
May I also get it?
My mail is vsdun3559cese@163.com
Thank you!
